# Generated by Django 5.0.7 on 2024-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
